### ISSUE TITLE
Smoothing of template and target very imbalanced before antsAI

### ISSUE THREAD

**Issue by oesteban** [nipreps/nibabies#1]
Looking at the antsAI (initialization) reports, it seems like the target is smoothed much more than the target. We will need to look into this and find a good tradeoff where the smoothing is more balanced (meaning, less smoothing for the target or more for the template).

https://github.com/nipreps/nibabies/blob/47cccc4b6cc7eaf14f825bfcaad3e2408d17c534/nibabies/workflows/brain_extraction.py#L416

**Comment by oesteban** [comment]
Actually, we need to probably switch to use `smooth=True` for `RegridToZooms`

https://github.com/nipreps/nibabies/blob/47cccc4b6cc7eaf14f825bfcaad3e2408d17c534/nibabies/workflows/brain_extraction.py#L102-L104

**Comment by mgxd** [comment]
closing since `RegridToZooms` has since been removed.
