### ISSUE TITLE
Execution begins but stops shortly after

### ISSUE THREAD

**Issue by mgxd** [nipreps/nibabies#140]
> The workflow should take some time to run..you won't be able to use that terminal window while it's running. Did the process stop?

_Originally posted by @mgxd in https://github.com/nipreps/nibabies/issues/134#issuecomment-942754978_

>Yes--it stopped after about a minute and gave me a fresh line on the terminal. It occurred to me that maybe I typed something so I tried it again and let it run but again it stopped after a minute. I can try submitting it as a job but I didn't see any log files created or any of the expected output. 
```
filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies $ ls
20211012-135552_0522ca0e-a7a5-4ae2-844b-ac07be695633  20211013-163101_870d6e99-94c8-4ae6-829a-0a1e77f9bfe7
20211012-135736_14e48429-9f7b-47f5-ad9e-1c9744482809  20211013-163731_43d6a8da-5175-4d23-9773-32b8bac81088
20211013-132003_a45aff65-7206-4965-8a93-b9458385703b  20211013-174049_60a417d9-9f9f-4ab5-b26e-7b1ac3657226
20211013-132151_15b0b3bb-0700-4cba-8238-96e04f2404d4  20211013-174937_2e444989-2b89-410d-8f98-96bf531e0fe5
20211013-154941_5fb278dd-bf26-4953-b89a-82a07e514dd2  20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354
20211013-155646_a2c71c63-8c4d-4f69-8dfb-a02aa546475a
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies $ cd 20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies/20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354 $ ls
bids_db  config.toml
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies/20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354 $ cd bids_db/
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies/20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354/bids_db $ ls
layout_index.sqlite
```

_Originally posted by @cfilippi4 in https://github.com/nipreps/nibabies/issues/134#issuecomment-942759170_

relevant log output:
```
[R21] (base) filippica@cn0943:/data/filippica/R21 $ nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -v --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt --notrack
/data/filippica/R21/code/conda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211013-17:40:59,400 cli INFO:
	 Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator does not appear to be installed
/data/filippica/R21/code/conda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211013-17:41:16,661 nipype.workflow IMPORTANT:

    Running nibabies version 0+unknown:
      * BIDS dataset path: /data/filippica/R21/BIDS/OIT.
      * Participant list: ['OIT022'].
      * Run identifier: 20211013-174049_60a417d9-9f9f-4ab5-b26e-7b1ac3657226.
      * Output spaces: MNIInfant:cohort-2:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /data/filippica/R21/derivatives/OIT/nibabies/sourcedata/infant-freesurfer.
/data/filippica/R21/code/conda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
211013-17:41:34,318 nipype.interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
211013-17:41:37,492 nipype.workflow INFO:
	 No single-band-reference found for sub-OIT022_ses-20180607_task-rest_run-191152_bold.nii.gz.
211013-17:41:37,493 nipype.workflow INFO:
	 Found usable B0 fieldmap <('auto_00000',)>
```

**Comment by mgxd** [comment]
> Hmmm...that line didn't run. I got an error that says "command not found".

Actually, I think it did run and that's what the exit code signifies. Looks like something is missing or just not found.

Overall, I think `nibabies` should unmask this and include a stack traceback to improve clarity and make it easier to track down.

In the meantime, do you have access to an environment with Docker or Singularity installed? This would include nibabies in a prepackaged environment, removing one variable in this effort to get it to successfully process your data.

**Comment by cfilippi4** [comment]
Hi again! 
So I'm not sure why but I'm still getting the same error even after installing the 21.0.0 via singularity. 
```
filippica@cn0867:/data/filippica/R21 $ module load nibabies/21.0.0 
[+] Loading nibabies  21.0.0  on cn0867 
[+] Loading singularity  3.8.2  on cn0867 
[R21] (base) filippica@cn0867:/data/filippica/R21 $  nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -vvv --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt --notrack
WARNING: While bind mounting '/gs10:/gs10': destination is already in the mount point list
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211019-14:46:39,401 cli INFO:
	 Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator@1.8.4

	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        Summary:                  Available Tasks:        Available Modalities: 
        727 Files, 20.17GB                                MRI                   
        54 - Subjects                                                           
        52 - Sessions                                                           


	If you have any questions, please post on https://neurostars.org/tags/bids.
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211019-14:46:52,311 nipype.workflow IMPORTANT:
	 
    Running nibabies version 21.0.0+0.gd898bf0.dirty:
      * BIDS dataset path: /data/filippica/R21/BIDS/OIT.
      * Participant list: ['OIT022'].
      * Run identifier: 20211019-144627_444c7331-b6ed-4787-9706-32a689b9b859.
      * Output spaces: MNIInfant:cohort-2:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /data/filippica/R21/derivatives/OIT/nibabies/sourcedata/infant-freesurfer.
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
211019-14:46:59,702 nipype.workflow INFO:
	 No single-band-reference found for sub-OIT022_ses-20180607_task-rest_run-191152_bold.nii.gz.
211019-14:46:59,702 nipype.workflow INFO:
	 Found usable B0 fieldmap <('auto_00000',)>
```

After it failed and gave a fresh line, I typed the troubleshooting commands you gave above....
```
filippica@cn0867:/data/filippica/R21 $ echo $?
247
filippica@cn0867:/data/filippica/R21 $ python -c "import os; print(os.strerror(247))"
Unknown error 247
```

**Comment by mgxd** [comment]
I started running the data with the same arguments you were using:

>nibabies-wrapper docker testdata/oit testdata/oit/derivatives/nibabies participant --age-months 4 -w testdata/work/oit --participant-label OIT022 --fs-license-file testdata/work/license.txt --fs-subjects-dir testdata/oit/derivatives/infant-freesurfer --mem 8GB --omp-nthreads 2 --nprocs 4 --random-seed 0 --error-on-aroma-warnings --fd-spike-threshold 0.2 --notrack -v -i nipreps/nibabies:21.0.2

I was able to get passed where you were stuck, so I don't think it is a data problem. So this points to some system / installation problem...Looking over https://github.com/nipreps/nibabies/issues/140#issuecomment-947011647 again, it is not clear to me what the actual singularity command being used is.

**Comment by cfilippi4** [comment]
HI Mathais,
So we got it to run on our system but it failed again.. Here's the message...

FYI: Your nibabies job failed just now with the following error:

******************************************************
211207-13:11:09,127 nipype.workflow CRITICAL:
	 nibabies failed: Workflow did not execute cleanly. Check log for details
211207-13:11:17,328 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: OIT022 (1). Check the HTML reports for details.

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nibabies", line 33, in <module>
    sys.exit(load_entry_point('nibabies', 'console_scripts', 'nibabies')())
  File "/src/nibabies/nibabies/cli/run.py", line 91, in main
    nibabies_wf.run(**config.nipype.get_plugin())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/tools.py", line 96, in report_nodes_not_run
    raise RuntimeError(
RuntimeError: Workflow did not execute cleanly. Check log for details
***********************************************************************

... and by looking at the logs the error seems to be when running infant_recon_all:

--------------------------
error: mghRead(/opt/freesurfer/average/CNYBCH/Template14/norm.mgz, -1): could not open file
-----------------------------

The directory "/opt" is inside the nibabies container. I looked inside the container and there is no "Template14" directory:

--------------------------------------
Singularity> ls /opt/freesurfer/average/CNYBCH/          
Template15  Template17	Template8  Template9
----------------------------------------

Our nibabies container is just a conversion from the Docker container provided by the developers. So perhaps we should ask Mathias about this "Template14" directory that is missing?

**Comment by mgxd** [comment]
Ah yes, this was a problem with the original `21.0.0` release not including all templates needed by `infant_recon_all`. This has been fixed in subsequent release (I'd recommend using the latest release `21.0.2`)

**Comment by cfilippi4** [comment]
Thanks! I'll update.

**Comment by cfilippi4** [comment]
So we updated to the latest release but when I re-ran the subject (not deleting any of the derivates files) I got the following error. 

--------------------------------------------
Node: nibabies_wf.single_subject_OIT022_wf.infant_anat_wf.infant_surface_recon_wf.reconall
Working directory: /gpfs/gsfs10/users/filippica/R21/tmp/derivatives/OIT/nibabies/nibabies_wf/single_subject_OIT022_wf/infant_anat_wf/infant_surface_recon_wf/reconall

Node inputs:

age = 4
args = <undefined>
aseg_file = <undefined>
environ = {}
mask_file = /gpfs/gsfs10/users/filippica/R21/tmp/derivatives/OIT/nibabies/nibabies_wf/single_subject_OIT022_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-OIT022_ses-20180607_run
-184837_T1w_corrected_masked.nii.gz
newborn = <undefined>
outdir = /data/filippica/R21/derivatives/OIT/nibabies/sourcedata/infant-freesurfer/sub-OIT022
subject_id = sub-OIT022
subjects_dir = <undefined>
t1_file = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node reconall.

RuntimeError: subprocess exited with code 1.

Any suggestions?
-C

**Comment by mgxd** [comment]
hm, that is a cryptic error message - is some other useful information in the stdout?

if not, within `/gpfs/gsfs10/users/filippica/R21/tmp/derivatives/OIT/nibabies/nibabies_wf/single_subject_OIT022_wf/infant_anat_wf/infant_surface_recon_wf/reconall` you will find a file `command.txt`, which is a copy of the command being executed. Running that may shed some light here

**Comment by cfilippi4** [comment]
I've attached the output file. 

I found the command.txt file. It reads...
```
infant_recon_all --age 4 --masked /gpfs/gsfs10/users/filippica/R21/tmp/derivatives/OIT/nibabies/nibabies_wf/single_subject_OIT022_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-OIT022_ses-20180607_run-184837_T1w_corrected_masked.nii.gz --outdir /data/filippica/R21/derivatives/OIT/nibabies/sourcedata/infant-freesurfer/sub-OIT022 --subject sub-OIT022
```

When I ran that command I get the following....
```
[filippica@cn0860 code]$ infant_recon_all --age 4 --masked /gpfs/gsfs10/users/filippica/R21/tmp/derivatives/OIT/nibabies/nibabies_wf/single_subject_OIT022_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-OIT022_ses-20180607_run-184837_T1w_corrected_masked.nii.gz --outdir /data/filippica/R21/derivatives/OIT/nibabies/sourcedata/infant-freesurfer/sub-OIT022 --subject sub-OIT022
bash: infant_recon_all: command not found
```


The command run was identical to the one used before the upgrade to the latest version (except now I load the newest version 21.0.2)
[slurm-28166314.txt](https://github.com/nipreps/nibabies/files/7678485/slurm-28166314.txt)
.

**Comment by mgxd** [comment]
You would have to run that within the singularity container. Your setup seems to be nontraditional, normally when using Singularity you would do the following:

1. Ensure `singularity` is in your PATH. In HPCs using modules, this generally requires a `module load <target-module>` command. You can test if Singularity is available by running `singularity version`.
2. Now with Singularity, you can build an image of the desired nibabies version.
```
singularity build <output/image.sif> docker://nipreps/nibabies:<release>
```
3. Once you have this image, you can either write the singularity command yourself, or use the [`nibabies-wrapper`](https://nibabies.readthedocs.io/en/latest/installation.html#installing-the-nibabies-wrapper) to have it generate it for you.

To enter the singularity container, you can use the `singularity shell` command. Just ensure you are bringing in the necessary bindings - in your case it would look something like (assuming /gpfs and /data are local paths):
```
singularity shell -e -B /gpfs:/gpfs -B /data:/data <nibabies-image>
```
Then you should have access to all executables required, including `infant_recon_all`.

Hope this helps clarify a little.
