### ISSUE TITLE
.html summary file gets overwritten when processing several sessions of one subject

### ISSUE THREAD

**Issue by moser297** [nipreps/nibabies#147]
### What happened?

When (independently) running several sessions of one subject and storing them in the same output foder (example folder structure: output/nibabies/sub-/ses-), the .html summary file produced by nibabies gets overwritten. This happens as the file does not have a session identifier (it's named sub-<ID>.html) and is located on the level above the subject folder (e.g. output/nibabies). 

### What command did you use?

```shell
./nibabies-21.0.0rc0.sif /data /out participant --age-months 10 \
--output-spaces MNIInfant:cohort-4 \
-w /work
```

### Version

21.0.0 release candidates (rc)

**Comment by mgxd** [comment]
Thanks for the report - indeed, creating individual reports per session would probably be the easiest way to get around this problem. I'll work on a fix for the next release - in the meantime, you could workaround this issue by creating multiple output directories for each session (i.e. nibabies-ses-1mo, nibabies-ses-5mo, etc). 

I think the bigger problem at hand is there is currently no easy and concise way to handle the processing of subjects with multiple sessions (spanning different ages). This was brought up in an [earlier issue](https://github.com/nipreps/nibabies/issues/75), in which I brainstormed some ideas. One question - how many session are you working with? I'm trying see whether it makes more sense to bundle all session into a single report, or spread them out.

**Comment by moser297** [comment]
Thanks for your quick reply! At the moment I'm working with data that has varying sessions per subject (one to five). For now, I'm using the workaround to create individual output folders for each session. I just wanted to bring this issue to your attention for making things easier in the future.

**Comment by mgxd** [comment]
Sounds good, thanks.

BTW, if you are processing many subjectds, I'd recommend using `21.0.1`, which should be more stable than a release candidate.

**Comment by mgxd** [comment]
nibabies will now create `sub-X_ses-Y.html` when using the `-s`/`--session-id` flag
