### ISSUE TITLE
default template 

### ISSUE THREAD

**Issue by a3sha2** [nipreps/nibabies#148]
Hello @mgxd and @effigies 

pls what is going to be default template for nibabies just like  `MNI152NLin2009cAsym` is default template for fMRIPrep

**Comment by mgxd** [comment]
hi @a3sha2 

Currently the default output space is the `MNIInfant` ([MNI Unbiased nonlinear Infant Atlases 0-4.5yr](http://nist.mni.mcgill.ca/infant-atlases-0-4-5-years/)). This includes 11 templates, and is automatically matched based on the provided `--age-months`
