### ISSUE TITLE
ModuleNotFoundError: No module named 'niworkflows.interfaces.segmentation'

### ISSUE THREAD

**Issue by cfilippi4** [nipreps/nibabies#168]
### What happened?

I got the following error:

ModuleNotFoundError: No module named 'niworkflows.interfaces.segmentation'

See attached output and error files. I think this is related to the --use-aroma command because when I previously tested without --use-aroma it ran to completion. 

Any suggestions?

[test2_usearoma_added_error.txt](https://github.com/nipreps/nibabies/files/7697761/test2_usearoma_added_error.txt)
[test2_usearoma_added.txt](https://github.com/nipreps/nibabies/files/7697762/test2_usearoma_added.txt)

### What command did you use?

```shell
module load nibabies/21.0.2 ; 	    nibabies /data/filippica/R21/BIDS/BCP-selected/ /data/filippica/R21/derivatives/BCP-selected/sub-116056.out participant --participant-label sub-116056 -w /data/filippica/R21/temp/BCP-selected/sub-116056.wrk --use-aroma --notrack --age-months 3 --omp-nthreads 1 --random-seed 0 --skull-strip-fixed-seed -v --fd-spike-threshold .25 --skip_bids_validation --fs-license-file /data/filippica/R21//lists/license.txt
```

### What version of NiBabies are you using?

21.0.2

### Relevant log output

```shell
See attached.
```

**Comment by mgxd** [comment]
This is a bug and will be fixed in the next release. Until then, you should be fine if you skip aroma processing
