### ISSUE TITLE
Age range for processing

### ISSUE THREAD

**Issue by jimzops** [nipreps/nibabies#175]
### A short summary of what you would like to see in *NiBabies*.

Does nibabies only work on bneonates through 2yo (0-24months)?
Can you process 3yo/36mo data?

### Do you have any interest in helping implement the feature?

Yes!

**Comment by mgxd** [comment]
hi @jimzops, sorry for the delay; the 24mo recommendation is because of the templates included with `infant_recon_all` - however, we have tested and seen decent results with 26mo+, so nibabies does not impose a cap.

Feel free to reopen if you have any follow up
