### ISSUE TITLE
Add Cohort Parsing Functionality into Nibabies itself

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#180]
### A short summary of what you would like to see in *NiBabies*.

Using the --age-months flag to decide the cohort used in the template_description.json.

Greg Conan wrote this (username: @gregconan) to be used in CABINET. We thought it might be more useful directly in Nibabies. Instead of incorporating it as a separate flag. You should be able to take what we have and add it in directly. Let us know if you have any questions.

### Do you have any interest in helping implement the feature?

Yes!

### Add any additional information or context about the request here.

```
    import json

    with open(template_description_json_path, 'r') as infile:
        template_description = json.load(infile)
    cohorts = template_description["cohort"]
    for cohort_num, cohort_details in cohorts.items():
        if (int(cohort_details["age"][0]) < int(age_months)
                                            < int(cohort_details["age"][1])):
            break
    print(cohort_num)
```

Where template description is this file:
https://raw.githubusercontent.com/templateflow/tpl-MNIInfant/master/template_description.json

One of the `<` in the if statement needs to be less than or equal to, but we were unsure which one based on the cohort age ranges.

**Comment by mgxd** [comment]
The `--age-months` flag already determines which cohort to best use: see https://github.com/nipreps/nibabies/blob/dcf63df685033fa94d98dcb4d352f4fe0df0d31a/nibabies/utils/misc.py#L44

**Comment by mgxd** [comment]
No - if `--output-spaces` isn't specified, the default will be set to MNIInfant:cohort-X, where X is the cohort determined by the function above using the value provided by `--age-months`

**Comment by hough129** [comment]
Oh perfect!
