### ISSUE TITLE
RuntimeError: 2 raised. Re-raising first.

### ISSUE THREAD

**Issue by cfilippi4** [nipreps/nibabies#199]
So I ran nibabies on roughly a hundred subjects and the pipeline failed for 8 subjects and I'm not sure why. All the error files list the same error (see below). I did a quick check and the raw data look fine and there's plenty of disk space. 

tail swarm_35013196_0.e

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nibabies", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/cli/run.py", line 91, in main
    nibabies_wf.run(**config.nipype.get_plugin())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: 2 raised. Re-raising first.

tail swarm_35013196_0.o

220324-16:51:41,12 nipype.workflow ERROR:
	 could not run node: nibabies_wf.single_subject_OIT183_wf.fmap_preproc_wf.wf_auto_00000.concat_blips
220324-16:51:41,12 nipype.workflow INFO:
	 crashfile: /data/filippica/R21/derivatives2/OIT/nibabies_0/sub-OIT183.out/sub-OIT183/log/20220324-143132_a5bf42a8-2aee-40f8-817d-c7b9d5103333/crash-20220324-143500-filippica-concat_blips-b9f29d3c-ecbc-464c-8ef7-d4f152e30ef3.txt
220324-16:51:41,12 nipype.workflow INFO:
	 ***********************************
220324-16:51:41,39 nipype.workflow CRITICAL:
	 nibabies failed: 2 raised. Re-raising first.
220324-16:51:43,104 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: OIT183 (4). Check the HTML reports for details.

Can you help us unpack the error message?

[swarm_35013196_0_error.txt](https://github.com/nipreps/nibabies/files/8352338/swarm_35013196_0_error.txt)
[swarm_35013196_0_output.txt](https://github.com/nipreps/nibabies/files/8352339/swarm_35013196_0_output.txt)

Crash files from /data/filippica/R21/derivatives2/OIT/nibabies_0/sub-OIT183.out/sub-OIT183/log/20220324-143132_a5bf42a8-2aee-40f8-817d-c7b9d5103333/ also attached.

[crash-20220324-163043-filippica-select_volumes-95160e8c-c1b2-40c6-9d2a-be40bfedfc06.txt](https://github.com/nipreps/nibabies/files/8352342/crash-20220324-163043-filippica-select_volumes-95160e8c-c1b2-40c6-9d2a-be40bfedfc06.txt)
[crash-20220324-143440-filippica-summary-d088f119-8863-4ea4-a51e-4a4d9f065fe1.txt](https://github.com/nipreps/nibabies/files/8352343/crash-20220324-143440-filippica-summary-d088f119-8863-4ea4-a51e-4a4d9f065fe1.txt)
[crash-20220324-143446-filippica-raw_sources-896f8eb5-9944-49e0-8f0c-ebb7fde74af8.txt](https://github.com/nipreps/nibabies/files/8352344/crash-20220324-143446-filippica-raw_sources-896f8eb5-9944-49e0-8f0c-ebb7fde74af8.txt)
[crash-20220324-143500-filippica-concat_blips-b9f29d3c-ecbc-464c-8ef7-d4f152e30ef3.txt](https://github.com/nipreps/nibabies/files/8352345/crash-20220324-143500-filippica-concat_blips-b9f29d3c-ecbc-464c-8ef7-d4f152e30ef3.txt)

**Comment by mgxd** [comment]
Thanks for the info - there is a lot but quickly looking at this, a few problems jump out:

1) You are reusing a working directory - was this previously run with a different nibabies version? This can sometimes cause problems - I'd recommend running on a fresh directory.

2) Looking at the `concat_blips` crash: some of your fieldmaps may have slightly different affines (perhaps very small, negligible amounts). This has come up in fmriprep (https://github.com/nipreps/fmriprep/issues/2706) - while we work on relaxing this requirement, you could try copying affines to make them all uniform (assuming that there is no substantial difference)

**Comment by mgxd** [comment]
@cfilippi4 the latest release (22.0.2) includes added tolerance for difference in affines - that should fix (2) above. I'm going to close this, but feel free to reopen or start a new issue if you are still running into issues
