### ISSUE TITLE
optimal combination of multi-echo data as done in fMRIprep

### ISSUE THREAD

**Issue by moser297** [nipreps/nibabies#210]
### A short summary of what you would like to see in *NiBabies*.

It would be great, if it would be possible to get an optimally combined time series as output of Nibabies when using multi-echo data as input. Is there an option to include the T2*-driven echo combination init_bold_t2s workflow from fMRIprep? The current version of Nibabies has a --multi-echo flag but the outputs are individual echos whether the flag is used or not. 

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by effigies** [comment]
We should be doing this. Could you share more details about what you're seeing?

**Comment by moser297** [comment]
I used Nibabies with a multi-echo BIDS folder as input calling: `./nibabies-22.0.1.sif /data /out participant --age-months 1 --output-spaces MNIInfant:cohort-1 -w /work`  and my outputs look the same as if I would add the `--me-output-echos` flag.  In both cases, it outputs a bold data file for each of the individual echos but no combined one.

**Comment by effigies** [comment]
I can't see anything obvious in the workflow that would explain this. Are you able to share your data?

**Comment by moser297** [comment]
Yes, sure! Do you or anybody else in the team have access to the UMN MSI? If yes, I can send you an email with the file paths. If no, I can create a box folder for it.
