### ISSUE TITLE
*slight* misalignment of surface to native T1w even after correct transform is applied

### ISSUE THREAD

**Issue by ericfeczko** [nipreps/nibabies#225]
### What happened?

I'm checking the surface alignment in workbench after resolution of this issue https://github.com/nipreps/nibabies/issues/222

The surfaces are still not aligned to the T1w despite the application of a clearly correct transform. After consulting with the HCP folk. They pointed out that the misalignment is an offset problem related to the metadata of the RAS coordinates -- this reflects the expectation that freesurfer inputs are not oblique -- normally not an issue but sometimes can happen with infants. New versions of mris_convert enable the use of the -to-scanner option. I was able to confirm outside of nibabies that this option both works and can replace the current workflow for using the fsnative transform. 
The problem stems from this line in nibabies:

https://github.com/nipreps/nibabies/blob/master/nibabies/workflows/anatomical/surfaces.py#L125

`         (gifti_surface_wf, outputnode, [
            ('outputnode.surfaces', 'surfaces'),` 
            
This is actually a central issue from smriprep: 
https://github.com/nipreps/smriprep/blob/master/smriprep/workflows/surfaces.py#L533

`    fs2gii = pe.MapNode(
        fs.MRIsConvert(out_datatype="gii"), iterfield="in_file", name="fs2gii"
    )
    fix_surfs = pe.MapNode(NormalizeSurf(), iterfield="in_file", name="fix_surfs")`

Specifically, the `fs.MRIsConvert` call should set the `--to-scanner` option to TRUE if the data are not pre-aligned before running freesurfer. The option is described here: https://github.com/nipy/nipype/blob/master/nipype/interfaces/freesurfer/utils.py#L1274
    
The fsnative2_xfm need not be applied to the surface -- as the solution above will resolve the need for such a transform.
    
Hope this helps!
    

### What command did you use?

```shell
I'm working off https://github.com/nipreps/nibabies/issues/222 -- I don't remember.
```

### What version of NiBabies are you using?

22.1.0.cr1

**Comment by hough129** [comment]
@ericfeczko is on vacation. I can have Jacob run this, so that Fez has results to look at / mess around with when he gets back.

**Comment by mgxd** [comment]
I'm going to close this, if it is still a problem please reopen!
