### ISSUE TITLE
Cifti subcortical BOLD is not conformed to LAS as in fMRIPrep

### ISSUE THREAD

**Issue by madisoth** [nipreps/nibabies#228]
### What happened?

`--cifti-output 91k` subcortical volume data is output in RAS orientation, unlike fMRIPrep which outputs LAS (which is consistent with HCP pipelines). 

fMRIPrep (but not NiBabies) uses niworkflows.interfaces.cifti _create_cifti_image (https://github.com/nipreps/niworkflows/blob/1f44298559cd3e8161c3fe9278e1037c39423d59/niworkflows/interfaces/cifti.py#L326), which includes a step to conform to LAS.

### What command did you use?

```shell
N/A
```

### What version of NiBabies are you using?

22.1.0rc1

**Comment by mgxd** [comment]
The easiest fix would be to wrap the [reorient image function](https://github.com/nipreps/niworkflows/blob/1f44298559cd3e8161c3fe9278e1037c39423d59/niworkflows/interfaces/cifti.py#L471) into a `Function` `Node` and call it after the [BOLD files are collected](https://github.com/nipreps/nibabies/blob/d352a212bf39d2a149a4355e9003c321e228f377/nibabies/workflows/bold/base.py#L900-L903).

Additionally, the [MNI152NLin6Asym volume](https://github.com/nipreps/nibabies/blob/d352a212bf39d2a149a4355e9003c321e228f377/nibabies/workflows/bold/alignment.py#L55) may also need to be reoriented.

I can get to this next week, but if you want to contribute and submit a PR feel free
