### ISSUE TITLE
docker: failed to register layer

### ISSUE THREAD

**Issue by anikaguha1** [nipreps/nibabies#248]
### What happened?

When trying to run nibabies with the following command:

docker run --platform linux/amd64 --rm -e DOCKER_VERSION_8395080871=20.10.17 -it -v /home/opt/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/anika/Choline_Subs/Choline_Subs/nibabies:/data:ro -v /home/anika/Choline_Subs/Choline_Subs/nibabies/output:/out nipreps/nibabies:22.1.3 /data /out participant --age-months 5 --participant-label sub-167 --skip_bids_validation --ignore slicetiming

 I run into this error message:

docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /opt/freesurfer/ASegStatsLUT.txt: invalid argument.

Any suggestions as to how to resolve? I tried running 'docker system prune` but this unfortunately did not resolve the error. 

### What command did you use?

```shell
docker run --platform linux/amd64 --rm -e DOCKER_VERSION_8395080871=20.10.17 -it -v /home/opt/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/anika/Choline_Subs/Choline_Subs/nibabies:/data:ro -v /home/anika/Choline_Subs/Choline_Subs/nibabies/output:/out nipreps/nibabies:22.1.3 /data /out participant --age-months 5 --participant-label sub-167 --skip_bids_validation --ignore slicetiming
```

### What version of NiBabies are you using?

22.1.3

### Relevant log output

```shell
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /opt/freesurfer/ASegStatsLUT.txt: invalid argument.
See 'docker run --help'.
```

**Comment by mgxd** [comment]
I believe this is a problem with your local Docker installation, can you try:
- Removing any persistent volumes
```
docker volume prune
```
- Updating Docker to the latest version

**Comment by mgxd** [comment]
@anikaguha1 please reopen if this problem was not solved
