### ISSUE TITLE
Distortion corrected images look distorted in the opposite direction (AP for PA acquisition)

### ISSUE THREAD

**Issue by moser297** [nipreps/nibabies#254]
### What happened?

In the datasets we recently processed, images after distortion correction look distorted in the direction opposite to the acquisition direction (AP direction in PA BOLD acquisition). Comparing them to the fmaps used for correction, it looks like they were "overcorrected". I'm happy to provide example data, if this is something you can not replicate in your testing datasets. 

### What command did you use?

```shell
env -i ${singularity} run --cleanenv \
-B ${in_dir}:/data:ro \
-B ${out_dir}:/out \
-B ~/Documents/license.txt:/opt/freesurfer/license.txt \
-B ${work_dir}:/work \
-B ${in_dir}/derivatives/precomputed/:/derivatives \
/home/faird/shared/code/external/pipelines/nibabies/nibabies_22.1.3.sif /data /out participant --participant-label ${SUB} -s ${SES} --age-months 1 \
--derivatives /derivatives \
--cifti-output 91k \
--topup-max-vols 2 \
--nprocs 128 \
--omp-nthreads 3 \
--resource-monitor \
-vv \
-w /work
```

### What version of NiBabies are you using?

22.1.3

**Comment by mgxd** [comment]
@moser297 @madisoth is this still a problem?
