### ISSUE TITLE
Alter FreeSurfer subjects to include session labels

### ISSUE THREAD

**Issue by mgxd** [nipreps/nibabies#288]
### A short summary of what you would like to see in *NiBabies*.

As we are moving to session-based processing, multiple runs of FreeSurfer can clash. We should probably alter `subject_id` to include the session information, like is mentioned in:
https://surfer.nmr.mgh.harvard.edu/fswiki/BIDS

### Do you have any interest in helping implement the feature?

Yes!

**Comment by oesteban** [comment]
@yasseraleman look at this
