### ISSUE TITLE
mcribs surfaces misaligned to anat after fix_surfs node

### ISSUE THREAD

**Issue by madisoth** [nipreps/nibabies#297]
### What happened?

In a 1mo subject tested with mcribs, the .surf.gii anat surface derivatives are misaligned with the native-space anat volumes, but the outputs of the fs2gii node (i.e. before the fsnative-T1w transform is applied in the fix_surfs node) are correctly aligned 

Subject has both T1w and T2w; --surface-recon-method mcribs and --derivatives (precomputed aseg/mask) were both used.

### What command did you use?

```shell
/opt/conda/bin/nibabies /bids_dir /output_dir participant --surface-recon-method mcribs --skip_bids_validation --omp-nthreads 3 --resource-monitor --cifti-output 91k -vv -w /wd --fd-radius 35 --derivatives /derivatives --participant-label XXXXXX --age-months 1
```

### What version of NiBabies are you using?

23.1.0.dev95+gcdae035 (mcribs build from 05182023)

**Comment by mgxd** [comment]
This should be fixed after #301, please reopen if not
