### ISSUE TITLE
T2* map not properly scaled to 2mm MNI

### ISSUE THREAD

**Issue by moser297** [nipreps/nibabies#320]
### What happened?

The T2* maps per run outputted by Nibabies for multi-echo data are not aligned with the 2mm NMI anatomicals (see screenshot)

<img width="808" alt="image" src="https://github.com/nipreps/nibabies/assets/90271498/fb528cbb-b182-4220-a76b-1e468c38d075">

@madisoth suggested that the BOLD-T1w transform step is missing

### What command did you use?

```shell
singularity run --cleanenv \
-B /nibabies_test_binds/enh_single-anat/nibabies/nibabies/:/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies \
-B /bids_in/:/bids_dir \
-B /nibabies:/output_dir \
-B /derivatives:/derivatives \
-B /work/:/wd \
-B /license.txt:/opt/freesurfer/license.txt \
/nibabies_unstable_10052023a.sif /bids_dir /output_dir participant \
--project-goodvoxels \
--output-spaces MNI152NLin6Asym:res-2 \
--surface-recon-method mcribs \
--omp-nthreads 3 \
--derivatives /derivatives/bibsnet \
--cifti-output 91k \
-vv \
-w /wd \
--fd-radius 35 \
--skip-bids-validation \
--participant-label <>
```

### What version of NiBabies are you using?

unstable

### Add any additional information or context about the problem here.

@madisoth provided an intermediate solution: 

antsApplyTransforms --default-value 0 --float 1 --input /work/nibabies_23_2_wf/single_subject_01_wf/func_preproc_ses_01_task_restME_run_04_echo_1_wf/bold_t2smap_wf/t2smap_node/T2starmap.nii.gz --interpolation LanczosWindowedSinc --output /T2star/sub-_ses-01_task-restME_run-04_space-real-MNI152NLin6Asym_res-2_T2starmap.nii.gz --reference-image /any/anat/sub-_ses-01_space-MNI152NLin6Asym_desc-preproc_T1w.nii.gz --transform /work/nibabies_23_2_wf/single_subject__01_wf/infant_anat_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration/ants_t1_to_mniComposite.h5 --transform /work/nibabies_23_2_wf/single_subject_ION0005_01_wf/func_preproc_ses_01_task_restME_run_04_echo_1_wf/bold_reg_wf/bbreg_wf/concat_xfm/out_fwd.tfm

**Comment by mgxd** [comment]
@moser297 is this specifically for the https://github.com/nipreps/nibabies/pull/316?

**Comment by moser297** [comment]
No it's not (tried it in both branches) and I actually saw the same thing in fMRIprep yesterday, when I was processing a multi-echo adult dataset.
