### ISSUE TITLE
Carpet plots for func runs in .html report

### ISSUE THREAD

**Issue by ajdneuro** [nipreps/nibabies#344]
### What happened?

I am wondering if there is a way to get the FD, carpet plots for each func run. Right now they aren't showing up in the .html reports. I also tried adding MNI152NLin2009cAsym as an output space, but this did not fix it. Thanks!

### What command did you use?

```shell
Singularity, version 23.0.1
NiBabies command: /opt/conda/envs/nibabies/bin/nibabies /data /out participant --skip_bids_validation --age-months 1 --fd-spike-threshold 0.3 --participant-label sub-M80302901 -w /scratch --output-spaces MNI152NLin2009cAsym
```

### What version of NiBabies are you using?

23.1.0

**Comment by mgxd** [comment]
@ajdneuro the carpet plots are currently only available if you are running with `--cifti-output`

**Comment by ajdneuro** [comment]
Great that worked, thank you!
