### ISSUE TITLE
Add `space-fsaverage` to `desc-reg` sphere files without space entity

### ISSUE THREAD

**Issue by tsalo** [nipreps/nibabies#366]
### A short summary of what you would like to see in *NiBabies*.

I've seen outputs from Nibabies with the following naming convention: `<source_entities>_hemi-<L|R>_desc-reg_sphere.surf.gii`. Based on [a discussion](https://mattermost.brainhack.org/brainhack/pl/deqrcp7pxf8bpcu14cq97tc4rr) with @effigies, it looks like this is a registration sphere from fsnative to fsaverage, so it would be clearer to include `space-fsaverage` in the filename.

Please correct me if that's not what this file is.

### Do you have any interest in helping implement the feature?

Yes!

**Comment by tsalo** [comment]
@mgxd I'm interested in implementing this. Should I target `master` or `docker/fit-apply`?

**Comment by mgxd** [comment]
hey @tsalo - awesome! `docker/fit-apply` merge is imminent, so definitely that one
