### ISSUE TITLE
24.0.0rc fails with `'MNIInfant not found in SpatialReferences` if ``cifti-output`` flag not used

### ISSUE THREAD

**Issue by scott-huberty** [nipreps/nibabies#375]
EDIT: Edited this message on Aug 6th to provide more background info.

### Background

#360 by @mgxd Added this function:

https://github.com/nipreps/nibabies/blob/38fb3fdc4741672458d78f5fac8ea3d608dc3f8d/nibabies/workflows/base.py#L953-L964

Used here:

https://github.com/nipreps/nibabies/blob/38fb3fdc4741672458d78f5fac8ea3d608dc3f8d/nibabies/workflows/base.py#L517-L525

___________

### The Problem

If `config.execution.output_spaces` is `None` (which I believe is the [default value](https://github.com/nipreps/nibabies/blob/38fb3fdc4741672458d78f5fac8ea3d608dc3f8d/nibabies/config.py#L429)), then Nibabies will add `MNIInfant:cohort-1:res-native` at this LOC:

https://github.com/nipreps/nibabies/blob/38fb3fdc4741672458d78f5fac8ea3d608dc3f8d/nibabies/workflows/base.py#L829-L832

Then`get_MNIInfant_key` will throw an error on that exact value that Nibabies just added on Line 830.... I.e.. for release candidate [24.0.0rc](https://github.com/nipreps/nibabies/releases/tag/24.0.0rc0),  a lot of my files that ran without issue on [23.1.0](https://github.com/nipreps/nibabies/releases/tag/23.1.0)  now _always_ hit the error:

`KeyError: 'MNIInfant not found in SpatialReferences: Spatial References: MNIInfant:cohort-1:res-native'`

<details><summary>Full Stack Trace</summary>

```
Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/bin/nibabies", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/run.py", line 62, in main
    retval = build_workflow(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/workflow.py", line 76, in build_workflow
    retval['workflow'] = init_nibabies_wf(config.execution.unique_labels)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/workflows/base.py", line 147, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/workflows/base.py", line 521, in init_single_subject_wf
    key=get_MNIInfant_key(spaces),
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/workflows/base.py", line 963, in get_MNIInfant_key
    raise KeyError(f'MNIInfant not found in SpatialReferences: {spaces}')
KeyError: 'MNIInfant not found in SpatialReferences: Spatial References: MNIInfant:cohort-1:res-native'
```

</details>

-------------------

- This error isn't very helpful because 1) MNIInfant _is_ in Spatial References, and 2) there's no further info on what should be changed.

- I checked locally, and on [23.1.0](https://github.com/nipreps/nibabies/releases/tag/23.1.0), the value of my Spatial Reference is the same:` MNIInfant:cohort-1:res-native`. The only difference on [24.0.0rc](https://github.com/nipreps/nibabies/releases/tag/24.0.0rc0) seems to be that this new function, `get_MNIInfant_key`  forces an error on this value. 

- If I modify the function to accept this value, then things seems to run okay again. But I'd like to understand what `get_MNIInfant_key` really expects before I submit a PR for what I presume to be a bug.

**Comment by mgxd** [comment]
IIRC, this was to deal with the MNIInfant -> MNI152NLin6Asym transformation required for CIFTI outputs, since we are using a saved transform from a 1x1x1 isotropic version of each. My guess is you aren't using the `--cifti-output` flag, hence running into that. Seems like we need to add a check to ensure this is not required if not requesting CIFTI outputs.

**Comment by scott-huberty** [comment]
> IIRC, this was to deal with the MNIInfant -> MNI152NLin6Asym transformation required for CIFTI outputs, since we are using a saved transform from a 1x1x1 isotropic version of each. My guess is you aren't using the `--cifti-output` flag, hence running into that. Seems like we need to add a check to ensure this is not required if not requesting CIFTI outputs.

Yeah you are exactly right. I can confirm that I was not using the `--cifti-output` flag, and if I do use it, I don't hit the error.

**Comment by mgxd** [comment]
@scott-huberty do you want to submit a PR? otherwise i can address this

**Comment by scott-huberty** [comment]
> @scott-huberty do you want to submit a PR? otherwise i can address this

Sure! I'll give it a shot. Feel free to assign me.
