### ISSUE TITLE
Piecewise subcortical alignment for CIFTI mapping

### ISSUE THREAD

**Issue by effigies** [nipreps/nibabies#49]
To have a persistent link, here's the current script from DCAN: [SubcorticalAlign_ROIs.sh](https://github.com/DCAN-Labs/dcan-infant-pipeline/blob/247e19e5441cc814cea2f23720caeeb6c6aeadf8/fMRISurface/scripts/SubcorticalAlign_ROIs.sh)

Note that this supersedes an older script: [SubcorticalAlign_MNI_Affine.sh](https://github.com/DCAN-Labs/dcan-infant-pipeline/blob/247e19e5441cc814cea2f23720caeeb6c6aeadf8/fMRISurface/scripts/SubcorticalAlign_MNI_Affine.sh)

**Comment by mgxd** [comment]
Checklist of [`wb_command`](https://humanconnectome.org/software/workbench-command)s that need to be Nipype-ized.

- [ ] `cifti-create-dense-from-template`
- [ ] `cifti-create-dense-timeseries`
- [ ] `cifti-dilate`
- [ ] `cifti-create-label`
- [ ] `cifti-resample`
- [ ] `cifti-separate`
- [x] ~[`cifti-smoothing`](https://github.com/nipy/nipype/blob/4e8f54d8e304dd940cfdc5d42f37288651bc8a03/nipype/interfaces/workbench/cifti.py#L117)~
- [ ] `volume-affine-resample`
- [ ] `volume-all-labels-to-rois`
- [ ] `volume-label-export-table`
- [ ] `volume-label-import`

**Comment by effigies** [comment]
Going to start on volume-resample.

**Comment by effigies** [comment]
I did not quite finish volume-resample. I'm not sure why they didn't just use flirt's apply transform, tbh.

**Comment by mgxd** [comment]
The only missing interface is for `-cifti-separate`, which has already been converted in https://github.com/nipy/nipype/pull/3306.

**Comment by effigies** [comment]
@mgxd Want to copy that one in here for now, so we don't need to wait on the review/release process in nipype?

**Comment by mgxd** [comment]
Yeah, that sounds like the fastest way forward
