### ISSUE TITLE
Syntax for execution

### ISSUE THREAD

**Issue by jerodras** [nipreps/nibabies#73]
Greetings, I am excited to try running the new pipeline on some infant data we have. I have pulled the docker image 0.1.0 and tried running with the following syntax (see below) but do not get very far. I have validated the BIDS structure using BIDS Validator v1.7.3-dev.0, and have also tried running with specifying --age-months (relatedly, is this postmenstrual age at scan? I have assumed postnatal age at scan). MacOS 10.15.7, iMac 2019. Any guidance would be appreciated! 

`docker run --rm -it -v /Applications/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/jerodrasmussen/Desktop/testnibabies:/data:ro -v /Users/jerodrasmussen/Desktop/testnibabies/derivatives:/out mgxd/nibabies:0.1.0 /data /out participant --participant-label sub-UPSIDE321`

_Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nibabies", line 33, in <module>
    sys.exit(load_entry_point('nibabies', 'console_scripts', 'nibabies')())
  File "/src/nibabies/nibabies/cli/run.py", line 17, in main
    parse_args()
  File "/src/nibabies/nibabies/cli/parser.py", line 706, in parse_args
    from ..utils.bids import validate_input_dir
ImportError: cannot import name 'validate_input_dir' from 'nibabies.utils.bids' (/src/nibabies/nibabies/utils/bids.py)_

The directory structure is as follows:

sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-01_T1w.json
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-01_T1w.nii.gz
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-01_T2w.json
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-01_T2w.nii.gz
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-02_T1w.json
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-02_T1w.nii.gz
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-02_T2w.json
sub-UPSIDE321/ses-20191024/anat/sub-UPSIDE321_ses-20191024_run-02_T2w.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-ap_dwi.bval
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-ap_dwi.bvec
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-ap_dwi.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-ap_dwi.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-01_dwi.bval
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-01_dwi.bvec
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-01_dwi.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-01_dwi.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-02_dwi.bval
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-02_dwi.bvec
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-02_dwi.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-02_dwi.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-06_dwi.bval
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-06_dwi.bvec
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-06_dwi.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_acq-pa_run-06_dwi.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-01_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-01_sbref.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-02_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-02_sbref.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-03_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-03_sbref.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-04_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-04_sbref.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-05_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-05_sbref.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-06_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-06_sbref.nii.gz
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-07_sbref.json
sub-UPSIDE321/ses-20191024/dwi/sub-UPSIDE321_ses-20191024_run-07_sbref.nii.gz
sub-UPSIDE321/ses-20191024/fmap/sub-UPSIDE321_ses-20191024_dir-AP_epi.json
sub-UPSIDE321/ses-20191024/fmap/sub-UPSIDE321_ses-20191024_dir-AP_epi.nii.gz
sub-UPSIDE321/ses-20191024/fmap/sub-UPSIDE321_ses-20191024_dir-PA_epi.json
sub-UPSIDE321/ses-20191024/fmap/sub-UPSIDE321_ses-20191024_dir-PA_epi.nii.gz
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-01_bold.json
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-01_bold.nii.gz
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-01_sbref.json
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-01_sbref.nii.gz
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-02_bold.json
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-02_bold.nii.gz
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-02_sbref.json
sub-UPSIDE321/ses-20191024/func/sub-UPSIDE321_ses-20191024_task-rest_run-02_sbref.nii.gz

**Comment by mgxd** [comment]
Hi @jerodras - this is the result of my testing exclusively without BIDS validation. I will submit a fix shortly.

In the meantime, you can add `--skip-bids-validation` to your command to avoid the error.

**Comment by jerodras** [comment]
`--skip-bids-validation` Solved the issue

**Comment by mgxd** [comment]
This should be fixed with the newest release (`0.1.1`)
