### ISSUE TITLE
Cannot process subject with multiple sessions of different ages.

### ISSUE THREAD

**Issue by kathy-snider** [nipreps/nibabies#75]
Since there is no way to supply the session to be processed, but we can only supply a single age-months, we cannot process a subject that has multiple sessions under its subject directory if the sessions were done at different ages (which is usually the case). Need a way to specify which session to process.

**Comment by mgxd** [comment]
Yeah, this is a good point - what I image the long-term solution being is deprecating the `--age-months` flag in favor of:
1. Parsing the [sessions file](https://bids-specification.readthedocs.io/en/stable/06-longitudinal-and-multi-site-studies.html#sessions-file) if working with multi-session data. This can list the ages per "timepoint" (session)
2. Grabbing the age from the root dataset level `participants.tsv` if it is a single session.

------

For now, to get around this, you can use the `--bids-file-filter` argument to [selectively filter files](https://fmriprep.org/en/stable/faq.html#how-do-i-select-only-certain-files-to-be-input-to-fmriprep). An example JSON for this case would look like:
```
{
  "fmap": {"session": "<target>", "datatype": "fmap"},
  "bold": {"session": "<target>", "datatype": "func", "suffix": "bold"},
  "sbref": {"session": "<target>", "datatype": "func", "suffix": "sbref"},
  "t2w": {"session": "<target>", "datatype": "anat", "suffix": "T2w"},
  "t1w": {"session": "<target>", "datatype": "anat", "suffix": "T1w"},
}
```
where `<target>` is replace with the session ses-`<id>`
