### ISSUE TITLE
Add T2w anatomical images to the report

### ISSUE THREAD

**Issue by LuciMoore** [nipreps/nibabies#87]
It would be good to include the T2w images in the html report as well for infants because the T2w has better contrast than the T1w in some studies and is therefore more useful for quality assessment of surface reconstruction

**Comment by effigies** [comment]
Probably the best visualization here would be to keep the surface contours constant and cycle through anatomical images as background.

**Comment by effigies** [comment]
The basic plots are here: https://github.com/nipreps/smriprep/blob/620216a2bee8620fd2d302b17cd968c32c90ea8e/smriprep/interfaces/reports.py#L169-L208. 

https://github.com/nipreps/niworkflows/blob/32a33d61ab64e262a4ebcf8afcf232d70c2f92b3/niworkflows/interfaces/reportlets/segmentation.py#L76-L109
