### ISSUE TITLE
cannot get past brain mask phase

### ISSUE THREAD

**Issue by cmpetty** [nipreps/nibabies#90]
**Describe the bug**
Stuck at the brainmasking phase 

**To Reproduce**
    Running nibabies version 0.1.2:

currently running within singularity to try and debug

I have bound my server directories and templateflow through to the singularity environment

```
nibabies /mnt/munin/Song/Lab/Chris/Infant_MRI/BIDS  /mnt/munin/Song/Lab/Chris/Infant_MRI/derivatives participant  --verbose  --fs-license-file /mnt/packages/freesurfer_v7.1.1/license.txt  --skip_bids_validation  --participant-label ${SUBJ}  --age-months 3  --nprocs 12  --omp-nthreads 12  --work-dir /mnt/munin/Song/Lab/Chris/Infant_MRI/work  --output-spaces UNCInfant:cohort-1 --stop-on-first-crash --debug all
```

If i select the UNCInfant:cohort-1 output space, then i get no masking:
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
    value = Path(value)  # Use pathlib's validation
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 994, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 649, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 633, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 530, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'brain_mask' trait of a _TemplateFlowSelectOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '[]' <class 'str'> was specified.

During handling of the above exception, another exception occurred:
```

If i use MNIInfant:cohort-1 it crashes out because there's a list of brainmasks:
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
    value = Path(value)  # Use pathlib's validation
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 994, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 649, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/miniconda/lib/python3.7/pathlib.py", line 633, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 530, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 't1w_file' trait of a _TemplateFlowSelectOutputSpec instance must be a pathlike object or string representing an existing file, but a value of "[PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-1_T1w.nii.gz'), PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-2_T1w.nii.gz')]" <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 430, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 537, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '[PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-1_T1w.nii.gz'), PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-2_T1w.nii.gz')]' for output 't1w_file' of a TemplateFlowSelect interface
```

If i specify a specific resolution MNIInfant:cohort-1:res-2, i still get the same as above:
```
traits.trait_errors.TraitError: The 't1w_file' trait of a _TemplateFlowSelectOutputSpec instance must be a pathlike object or string representing an existing file, but a value of "[PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-1_T1w.nii.gz'), PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-2_T1w.nii.gz')]" <class 'str'> was specified.
```

If i delete res-1 from my templateflow directory, it just gets re-downloaded and i get the same crash as above with the list error.

If i remove stop at first crash the pipeline moves on, but i never get my functional output.

**Comment by mgxd** [comment]
Thanks for the report!

I think in the `UNCInfant:cohort-1` case, it is certainly a bug - probably due to an oversight with how the UNCInfant template is labeled vs the others in templateflow. I'll take a look soon, but for now, I would avoid using it as an output space.

For `MNIInfant:cohort-1`, you'll have to specify the resolution you would like - something like `MNIInfant:cohort-1:res-1` should do the trick. Perhaps in the next release, we can default to `res-1` whenever a template is specified without a resolution.

**Comment by cmpetty** [comment]
Thanks for the feedback, i suspected that the lack of res in the UNCInfant could be problematic, so i'd tried MNIInfant:cohort-1:res-2, which produced this error:

```
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 65, in get
    Path(p) for p in TF_LAYOUT.get(template=template, return_type="file", **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 631, in get
    raise ValueError(msg + "If you're sure you want to impose "
ValueError: 'res' is not a recognized entity. If you're sure you want to impose this constraint, set invalid_filters='allow'.
```

Thats why i ended up removing the res-# part of the input, which resulted in the two mask list from above.

My full command is below:
```
#nibabies
singularity run --cleanenv -B ${PACKDIR}:/mnt/packages -B /mnt/munin/Song/Lab/Chris/templateflow:$SINGULARITYENV_TEMPLATEFLOW_HOME /usr/local/packages/singularity/images/nibabies_v0.1.2.sif \
 /mnt/munin/Song/Lab/Chris/Infant_MRI/BIDS \
 /mnt/munin/Song/Lab/Chris/Infant_MRI/derivatives participant \
 --verbose \
 --fs-license-file /mnt/packages/freesurfer_v7.1.1/license.txt \
 --skip_bids_validation \
 --participant-label ${SUBJ} \
 --age-months 3 \
 --nprocs 12 \
 --omp-nthreads 12 \
 --work-dir /mnt/munin/Song/Lab/Chris/Infant_MRI/work \
 --output-spaces MNIInfant:cohort-1:res-1 \
 --skull-strip-template MNIInfant:cohort-1:res-1 \
 --debug all

```

**Comment by mgxd** [comment]
Hmm, it seems the `res` field is not being expanded, can you try with `--skull-strip-template MNIInfant:cohort-1:resolution-1` instead?

**Comment by cmpetty** [comment]
I still get the list error where it tries to pull 2 images:

traits.trait_errors.TraitError: The 't1w_file' trait of a _TemplateFlowSelectOutputSpec instance must be a pathlike object or string representing an existing file, but a value of "[PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-1_T1w.nii.gz'), PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-2_T1w.nii.gz')]" <class 'str'> was specified.


FileNotFoundError: No such file or directory '[PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-1_T1w.nii.gz'), PosixPath('/opt/templateflow/tpl-MNIInfant/cohort-1/tpl-MNIInfant_cohort-1_res-2_T1w.nii.gz')]' for output 't1w_file' of a TemplateFlowSelect interface


Config:

210806-07:14:43,193 nipype.workflow VERBOSE:
	 nibabies config:
		[environment]
		cpu_count = 48
		exec_env = "posix"
		overcommit_policy = "heuristic"
		overcommit_limit = "50%"
		nipype_version = "1.6.1"
		templateflow_version = "0.7.1"
		version = "0.1.2"
		
		[execution]
		bids_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/BIDS"
		bids_database_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/work2/20210806-071356_16738f19-13c0-4b31-b942-49fc65a5fb05/bids_db"
		bids_description_hash = "edf347174a00e1d161d718241b0ed7005d890f330aa0334c1d3add282b8b7a62"
		boilerplate_only = false
		sloppy = false
		debug = [ "compcor", "registration", "fieldmaps",]
		fs_license_file = "/mnt/packages/freesurfer_v7.1.1/license.txt"
		fs_subjects_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/derivatives/freesurfer-infant"
		layout = "BIDS Layout: ...Song/Lab/Chris/Infant_MRI/BIDS | Subjects: 1 | Sessions: 1 | Runs: 2"
		log_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/derivatives/nibabies/logs"
		log_level = 15
		low_mem = false
		md_only_boilerplate = false
		nibabies_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/derivatives/nibabies"
		notrack = false
		output_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/derivatives"
		output_layout = "legacy"
		output_spaces = "MNIInfant:cohort-1:resolution-1"
		reports_only = false
		run_uuid = "20210806-071356_16738f19-13c0-4b31-b942-49fc65a5fb05"
		participant_label = [ "0001",]
		templateflow_home = "/opt/templateflow"
		work_dir = "/mnt/munin/Song/Lab/Chris/Infant_MRI/work2"
		write_graph = false
		
		[workflow]
		age_months = 3
		anat_only = false
		aroma_err_on_warn = false
		aroma_melodic_dim = -200
		bold2t1w_dof = 6
		bold2t1w_init = "register"
		cifti_output = false
		fmap_bspline = false
		force_syn = false
		hires = true
		ignore = []
		longitudinal = false
		medial_surface_nan = false
		regressors_all_comps = false
		regressors_dvars_th = 1.5
		regressors_fd_th = 0.5
		run_reconall = false
		skull_strip_fixed_seed = false
		skull_strip_template = "MNIInfant:cohort-1:resolution-1"
		skull_strip_t1w = "force"
		spaces = "MNIInfant:cohort-1:resolution-1"
		use_aroma = false
		use_syn_sdc = false
		
		[nipype]
		crashfile_format = "txt"
		get_linked_libs = false
		nprocs = 12
		omp_nthreads = 12
		plugin = "MultiProc"
		resource_monitor = false
		stop_on_first_crash = true
		
		[seeds]
		master = 43810
		ants = 8651
		
		[nipype.plugin_args]
		maxtasksperchild = 1
		raise_insufficient = false

**Comment by cmpetty** [comment]
If I run with T1w as my output space the pipeline completes and I get all outputs, including functionals, in my selected space.

The UNC infant template is auto-selected correctly for my skull strip template:
skull_strip_template = "UNCInfant:cohort-1"

**Comment by mgxd** [comment]
Thanks for debugging. I was able to replicate and track down at least some of the problem. I'm working on a fix - once that's in I will cut a new bug fix release.

**Comment by cmpetty** [comment]
i may have jumped ahead slightly, since it hasn't been merged, but i pulled your updates to test

When i specified a specific resolution :  MNIInfant:cohort-1:res-2, the res got passed as a string, which crashed.

```
traits.trait_errors.TraitError: Each element of the 'resolution' trait of a _TemplateFlowSelectInputSpec instance must be an integer (int or long), but a value of '2' <class 'str'> was specified.

Error setting node input:
Node: select_tpl
input: resolution
results_file: /mnt/munin/Song/Lab/Chris/Infant_MRI/work/nibabies_wf/single_subject_0001_wf/infant_anat_wf/anat_derivatives_wf/_in_tuple_MNIInfantcohort-1.cohort1.res2/set_tpl_res/result_set_tpl_res.pklz
value: 2
```

When i removed the res-2, the selection defaults to 1 and the pipeline continued on with a single resolution as expected

**Comment by mgxd** [comment]
good catch - should be addressed in b83b868

**Comment by mgxd** [comment]
@cmpetty

**Comment by cmpetty** [comment]
@mgxd 

I pulled and tested.  While i did manage to get the output i asked for ( MNIInfant:cohort-1:res-2 ), the bold runs were not actually in that output space.

They were in that size, but not properly normalized to the template within the space.

```
[cmp12@blade17 func]$ mrinfo sub-0001_ses-01_task-rest_run-2_space-MNIInfant_cohort-1_res-2_desc-preproc_bold.nii.gz
************************************************
Image name:          "sub-0001_ses-01_task-rest_run-2_space-MNIInfant_cohort-1_res-2_desc-preproc_bold.nii.gz"
************************************************
  Dimensions:        98 x 117 x 80 x 420
  Voxel size:        2 x 2 x 2 x 0.8
  Data strides:      [ 1 2 3 4 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         signed 16 bit integer (little endian)
  Intensity scaling: offset = 4255.62890625, multiplier = 0.15922772884368896
  Transform:                    1           0          -0       -96.5
                                0           1          -0      -134.5
                                0           0           1       -72.5
  comments:          xform matrices modified by FixHeaderApplyTransforms (niworkflows v1.4.0rc6).
```

The anatomicals were in the correct space, but not the bold.

In this image you can see my T1 in gw, the MNIInfant:cohort-1:res-2 template in blue, with the boldref labeled as the correct space in red

<img width="940" alt="Screen Shot 2021-08-20 at 1 18 00 PM" src="https://user-images.githubusercontent.com/2243287/130271184-dd8cbc81-1dc6-4cbc-ba12-ebec95eeda8c.png">

you can see the full output here:
[https://shadow.biac.duke.edu/petty/derivatives/nibabies/sub-0001.html](url)

**Comment by mgxd** [comment]
thanks for the report @cmpetty - I've opened a new issue with this new issue. I am looking into this
